#ifndef VARIANTDATA_H
#define VARIANTDATA_H

#include "Census.h"

#include "clang/Tooling/Core/Replacement.h"
#include "llvm/Support/Error.h"

struct VariantFieldData {
    bool isFptr_;
    std::string name_;
    std::string value_;
    OpLocation location_;
};

using VariantKey = std::string;
struct VariantData {
    VariantKey name_;
    OpLocation location_;
    std::unordered_map<std::string, VariantFieldData> attrs_;    // attr: <enum field> = <enum field's value>
};
std::unordered_map<std::string, VariantData> Variants;

std::string variantFieldTag(VariantFieldData const &field) {
    std::string tag = field.name_;
    std::string suffix = " sub)";
    if(field.isFptr_) {
        auto ppos = field.name_.find_last_of('(');
        if(ppos != std::string::npos) {
            tag.replace(ppos, 1, "(*sub)(");
            suffix = ")";
        }
    }
    return tag + suffix;
}

std::vector<std::string> makeVariantAnnotations(VariantData const &vd) {
    // Tag format
    // int __ENUM_Shape_2(struct Shape base, struct Rectangle sub) { return 0; }
    //           |_fn_|  |------base--------|-----subtype----|
    // |-------prefix--|n|-----------------------------------|--^--|--suffix---|
    //
    auto fn = vd.name_;
    std::string toDelete = "struct "; // Don't include struct in fn name
    if(auto pos = fn.find(toDelete); pos != std::string::npos) {
        fn.replace(pos, toDelete.size(), "");
    }
    std::string prefix = "int __ENUM_" + fn + "_";
    std::string base = "(" + vd.name_ + " base, ";
    std::string suffix = " { return 0; }\n";

    unsigned n = 0;
    std::vector<std::string> tags;
    tags.reserve(vd.attrs_.size());
    for(auto const &[field, fdata]: vd.attrs_) {
        std::string tag = prefix + std::to_string(n)    // fn
                            + base                      // base param
                            + variantFieldTag(fdata)    // subtype param
                            + suffix;                   // body
        tags.push_back(tag);
        n++;
    }
    return tags;
}

std::string blockAnnotation(std::vector<VariantKey> const &variants) {
    std::string insertPrefix = "\n// Tags generated by TCC //\n";

    auto nbTags = std::accumulate(begin(variants), end(variants), 0,
            [](unsigned count, auto const &v) {
                return count + Variants[v].attrs_.size();
            });
    std::vector<std::string> tags;
    tags.reserve(nbTags);

    for(auto const &v: variants) {
        auto vtags = (makeVariantAnnotations(Variants[v]));
        tags.insert(std::end(tags), std::begin(vtags), std::end(vtags));
    }
    std::string annotation;
    for(auto const &t: tags) {
        annotation += t;
    }

    std::string insertSuffix = "// end Tags generated by TCC //\n";
    return insertPrefix + annotation + insertSuffix;
}

llvm::Expected<Replacements> eofVariantBlockAnnotation(clang::SourceManager const &sm,
        FileID fid,
        std::vector<VariantKey> const &variants) {

    auto insertLoc = sm.getLocForEndOfFile(fid);
    Replacements repls;
    auto err = repls.add(Replacement(sm, insertLoc, 0, blockAnnotation(variants)));
    if(err) {
        auto fp = sm.getFilename(insertLoc);
        CNS_ERROR("BlockRepl", "Could not schedule block annotation insertion for {}", fp.str());
        return err;
    }
    return repls;
}

llvm::Expected<std::string> addVariantTagsToSourceBuffer(clang::SourceManager const &sm,
        FileID fid,
        FileEntryRef fr,
        std::string const &fp,
        std::vector<VariantKey> const &variants) {

    constexpr auto logKey = "InsertTag";

    auto replacements = eofVariantBlockAnnotation(sm, fid, variants);
    if(!replacements) {
        CNS_ERROR(logKey, "Block replacement failed for {}", fp);
        auto err = replacements.takeError();
        return err;
    }

    auto fb = llvm::MemoryBuffer::getFile(fp);
    if(!fb) {
        CNS_ERROR(logKey, "Read failed for {}: {}", fp, fb.getError().message());
        return llvm::errorCodeToError(fb.getError());
    }

    /*
    SmallVectorImpl<char> fpp;
    fpp.append(std::begin(fr.getName().str()), std::end(fr.getName().str()));
    auto fixed = sm.getFileManager().FixupRelativePath(fpp);
    if(fixed) {
        auto fb = sm.getFileManager().getBufferForFile(fpp);
        if(!fb) {
            CNS_ERROR(logKey, "getBuffer failed for {}: {}", fp, fb.getError().message());
            return llvm::errorCodeToError(fb.getError());
        }
        std::string old = fb.get()->getBuffer().str();
        return applyAllReplacements(old, *replacements);
    }
    */

    /*
    auto fb = sm.getFileManager().getBufferForFile(fr);
    if(!fb) {
        CNS_ERROR(logKey, "getBuffer failed for {}: {}", fp, fb.getError().message());
        return llvm::errorCodeToError(fb.getError());
    }
    */

    std::string old = fb.get()->getBuffer().str();
    return applyAllReplacements(old, *replacements);
}

llvm::ErrorOr<std::string> variantTaggedRelativeOutPath(std::string const &fp, std::string const &outdir) {
    constexpr auto logKey = "VariantTaggedOutfile";

    llvm::SmallString<256> current;
    auto err = llvm::sys::fs::current_path(current);
    if(err) {
        CNS_ERROR(logKey, "Failed to get current path: {}", err.message());
        return err;
    }
    std::string common = current.c_str();
    CNS_DEBUG(logKey, "current path: {}", common);

    std::string outfile = outdir + "/" + fp;
    if(auto pos = fp.find(common); pos != std::string::npos) {
        // remove common path prefix
        CNS_DEBUG(logKey, "Relative path: ./{}", fp.substr(common.size()));
        outfile = outdir + fp.substr(common.size());
    }
    CNS_DEBUG(logKey, "Outfile path: {}", outfile);
    return outfile;
}

llvm::ErrorOr<std::string> prepVariantTaggedOutDir(std::string const &fp, std::string const &outdir) {
    constexpr auto logKey = "VariantTaggedOutfile";
    auto err = llvm::sys::fs::create_directories(outdir);
    if(err) {
        CNS_ERROR(logKey, "Create directory failed for {}: {}", outdir, err.message());
        return err;
    }

    auto outfile_ = variantTaggedRelativeOutPath(fp, outdir);
    if(!outfile_) {
        CNS_ERROR(logKey, "Cannot determine outfile path for {}: {}", fp, outfile_.getError().message());
        return outfile_.getError();
    }
    auto outfile = *outfile_;
    CNS_DEBUG(logKey, "Outfile path: {}", outfile);

    auto outdirs = outfile.substr(0, outfile.find_last_of('/'));
    if(outdir != outdirs) {
        // Create dirs in outfile path
        auto rc = llvm::sys::fs::create_directories(outdirs);
        if(rc) {
            CNS_ERROR(logKey, "Create directories failed for {}: {}", outdirs, rc.message());
            return rc;
        }
    }

    err = llvm::sys::fs::copy_file(fp, outfile);
    if(err) {
        CNS_ERROR(logKey, "File copy from {} to {} failed: {}", fp, outfile, err.message());
        return err;
    }
    return outfile;
}

void createVariantAnnotatedVersion(std::string fp, std::string outdir, std::string const &code) {
    constexpr auto logKey = "VariantTaggedOutfile";
    auto outfile_ = prepVariantTaggedOutDir(fp, outdir);
    if(!outfile_) {
        CNS_ERROR(logKey, "Error during variant tagged outfile creation for ({}) in outdir {}: {}", fp, outdir, outfile_.getError().message());
        return;
    }
    auto outfile = *outfile_;
    std::error_code rc;
    llvm::raw_fd_ostream os(outfile, rc, llvm::sys::fs::OF_Text);
    if(rc) {
        CNS_ERROR(logKey, "Write failed for {}: {}", outfile, rc.message());
        return;
    }
    os << code;
}

using FileToVariantsMap = std::unordered_map<std::string, std::vector<std::string>>;

void insertVariantTagsInMatchingSources(
        clang::SourceManager &sm,
        FileToVariantsMap const &variantsByFile,
        std::string const &outDir) {

    constexpr auto logKey = "InsertTag";
    for(auto it = sm.fileinfo_begin(); it != sm.fileinfo_end(); ++it) {
        auto const feref = it->first;
        auto const fname = realPathFromFileEntryRef(sm, feref);

        if(variantsByFile.find(fname) == std::end(variantsByFile)) {
            CNS_ERROR(logKey, "No variants found for filename {}", fname);
            continue;
        }

        auto fid = sm.getOrCreateFileID(feref, clang::SrcMgr::C_User);

        auto updatedCode = addVariantTagsToSourceBuffer(sm, fid, feref, fname, variantsByFile.at(fname));
        if(!updatedCode) {
            CNS_ERROR(logKey, "Variants annotation in source buffer failed for {}: {}", fname, llvm::toString(updatedCode.takeError()));
            continue;
        }
        createVariantAnnotatedVersion(fname, outDir, *updatedCode);
    }
}

#endif // VARIANTDATA_H
